export const paymentReceivedQueueName = 'payment-received'
export const paymentsReadyQueueName = 'payment-ready-to-send'
export const paymentCompleteQueueName = 'payment-complete'
export const paymentStartedQueueName = 'payment-started'
export const notificationsQueueName = 'notify-payment-complete'
